import React, { useEffect, useState } from 'react'
import axios from 'axios'
//import { useParams } from 'react-router-dom';
import { jsPDF } from "jspdf";
import Navbar from '../layout/Navbar';

export default function Home({ id, logout }) {
    // const { id } = useParams();

    const [users, setUsers] = useState([])

    const [fname, setfName] = useState("");
    const [lname, setlName] = useState("");

    useEffect(() => {
        const loadUsers = async () => {

            const result = await axios.get(`http://localhost:8080/Project1-1.0-SNAPSHOT/api/salary?empId=${id}`);
            setUsers(result.data);

            console.log(result.data[0]);
            setfName(result.data[0].employee_id.first_name);
            setlName(result.data[0].employee_id.last_name);
        }
        loadUsers();
        // eslint-disable-next-line
    }, []);




    function generatePDF(user) {
        const doc = new jsPDF()
        // doc.setFont("times");
        //doc.setFontType("bold");
        doc.setFontSize(18);
        doc.text('International Institue of Information Technology, Bangalore', 30, 10);

        doc.text('-------------------------------------------------------------------------------------------', 10, 20);
        doc.text('Salary Slip', 80, 30);
        doc.setFontSize(12);
        doc.text('-----------------------------', 75, 40);
        doc.setFontSize(12);
        // //doc.setFontType('normal');
        doc.setFont("times")
        doc.text('Employee Name ', 20, 50);
        doc.text(user.employee_id.first_name, 80, 50);
        doc.text(user.employee_id.last_name, 95, 50)
        doc.text('Employee Id ', 20, 60);
        doc.text(user.employee_id.employee_id.toString(), 80, 60);
        doc.text('Email_id ', 20, 70);
        doc.text(user.employee_id.email, 80, 70);
        doc.text('Title ', 20, 80);
        doc.text(user.employee_id.title, 80, 80);
        doc.text("Department ", 20, 90);
        doc.text(user.employee_id.department.name, 80, 90);
        doc.text('Date ', 20, 100);
        doc.text(user.payment_date, 80, 100);
        doc.text('Amount ', 20, 110);
        doc.text(user.amount.toString(), 80, 110);
        doc.text('Description ', 20, 120);
        doc.text(user.description, 80, 120);
        doc.text('---------------------------------------------------------------------------------------------------', 20, 130);
        doc.text('This is an autogenerated PDF therefore does not require any signature', 20, 140);

        doc.save(user.id.toString() + user.employee_id.first_name + ".pdf");
        alert("Salary Slip Downloaded Successfully");
    }

    return (

        <div>
            <Navbar heading={"Welcome, " + fname + " " + lname} buttonName={"Logout"} buttonLink={logout} />
            <div className="Container">
                <div className="py-4">
                    <table className="table border shadow">
                        <thead>
                            <tr>
                                <th scope="col">Employee ID</th>
                                <th scope="col">First Name</th>
                                <th scope="col">Last Name</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Date</th>
                                <th scope="col">Salary Slip</th>
                            </tr>
                        </thead>
                        <tbody>
                            {users.map((user, index) => (
                                <tr>
                                    <td>{user.employee_id.employee_id}</td>
                                    <td>{user.employee_id.first_name}</td>
                                    <td>{user.employee_id.last_name}</td>
                                    <td>{user.amount}</td>
                                    <td>{user.payment_date}</td>
                                    <td>
                                        <button className="btn btn-primary mx-2" onClick={() => generatePDF(user)}>Download</button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    )
}
